import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import DefaultHeader from '@/components/Header/DefaultHeader'

// const DefaultHeader = dynamic(() => import('@/components/Header/DefaultHeader.jsx'), {
//   loading: () => <p>Loading...</p>,
//   ssr: true
// })

// const DefaultFooter = dynamic(() => import('@/components/Footer/DefaultFooter.jsx'), {
//   loading: () => <p>Loading...</p>,
//   ssr: true
// })

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <DefaultHeader/>
        </header>
        {children}
        <footer className="footer">
          {/* <DefaultFooter/> */}
        </footer>
        </body>
    </html>
  );
}
// import { Inter } from "next/font/google";
// import "./globals.css";
// import dynamic from "next/dynamic";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const DefaultHeader = dynamic(() => import('@/components/Header/DefaultHeader.jsx'), {
//   loading: () => <p>Loading...</p>,
//   ssr: true
// });

// const DefaultFooter = dynamic(() => import('@/components/Footer/DefaultFooter.jsx'), {
//   loading: () => <p>Loading...</p>,
//   ssr: true
// });

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <header className="header">
//           <DefaultHeader />
//         </header>
//         {children}
//         <footer className="footer">
//           <DefaultFooter />
//         </footer>
//       </body>
//     </html>
//   );
// }
