name: Deploy
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Deps
        run: |
          npm ci
          npm run build
      - name: Upload FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
